name: whatsapp_clone_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  badges: ^3.1.2
  chat_bubbles: ^1.7.0
  flutter:
    sdk: flutter
  flutter_advanced_avatar: ^1.5.2
  flutter_contacts: ^1.1.9+2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  get: null
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  permission_handler: ^11.3.1
  story_view: ^0.16.5
  supabase_flutter: ^2.8.3
  timeago: null

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
